version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - getname
 # Php-fpm configuration
  php:
    # image: php:7.2-fpm
    build: .
    container_name: fpmcontainer
    links:
      - docker-mysql
    depends_on:
      - docker-mysql
    volumes:
      - .:/var/www/html
      # - ./php:/usr/local/etc/php/php.ini
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=get_name
      - DB_USERNAME=root
      - DB_PASSWORD=
    networks:
      - getname
 # Mysql configuration
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql-demo
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
        # - MYSQL_ROOT_PASSWORD=password
        # - MYSQL_USER=getname
        # - MYSQL_DATABASE=get_name
        # - MYSQL_PASSWORD=W0rdprestaBapaworD
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: get_name
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
        - "9906:3306"
    volumes:
        - ./dbdata:/var/lib/mysql
    networks:
      - getname
volumes:
  dbdata:

networks:
  getname:
    driver: bridge