version: '3'
services:
  haproxy:
    image: haproxy:latest
#    build: ./haproxy
    container_name: haproxy
    ports:
      - "9906:3306"
      - "4040:80"
    depends_on:
      - percona1
      - percona2
      - percona3
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /run/haproxy/
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - getname
  percona1:
    image: percona/percona-xtradb-cluster:latest
    container_name: percona1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - CLUSTER_NAME=mycluster
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./dbdata1:/var/lib/mysql
    networks:
      - getname
  percona2:
    image: percona/percona-xtradb-cluster:latest
    container_name: percona2
    depends_on:
      - percona1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - CLUSTER_NAME=mycluster
      - JOIN_IP=percona1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./dbdata2:/var/lib/mysql
    networks:
      - getname
  percona3:
    image: percona/percona-xtradb-cluster:latest
    container_name: percona3
    depends_on:
      - percona1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - CLUSTER_NAME=mycluster
      - JOIN_IP=percona1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./dbdata3:/var/lib/mysql
    networks:
      - getname
  # Nginx server configuration
  web:
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - haproxy
      - php
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - getname
 # Php-fpm configuration
  php:
    build: .
    container_name: fpmcontainer
    depends_on:
      - haproxy
    volumes:
      - .:/var/www/html
#       - ./php:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=haproxy
      - DB_PORT=3306
      - DB_DATABASE=get_name
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - getname
volumes:
  dbdata1:
  dbdata2:
  dbdata3:
networks:
  getname:
    driver: bridge