version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - docker-mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - getname
 # Php-fpm configuration
  php:
    # image: php:7.2-fpm
    build: .
    container_name: fpmcontainer
    depends_on:
      - docker-mysql
    volumes:
      - .:/var/www/html
      # - ./php:/usr/local/etc/php/php.ini
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOST=docker-mysql
      - DB_PORT=3306
      - DB_DATABASE=get_name
      - DB_USERNAME=getname
      - DB_PASSWORD=getname
    networks:
      - getname
 # Mysql configuration
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql-demo
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: get_name
      MYSQL_USER: getname
      MYSQL_PASSWORD: getname
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9906:3306"
    volumes:
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./dbdata:/var/lib/mysql
    networks:
      - getname
volumes:
  dbdata:

networks:
  getname:
    driver: bridge