FROM haproxy
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
#RUN mkdir -p /run/haproxy/ && chmod 777 /run/haproxy/
#RUN mkdir -p /run/haproxy/ && chmod 777 /run/haproxy/
#RUN haproxy -f /etc/haproxy/haproxy.cfg
